jenkins:
  remotingSecurity:
    enabled: true
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "chocolateen"
          name: "Hugo"
          password: ${USER_CHOCOLATEEN_PASSWORD}
        - id: "vaugie_g"
          name: "Garance"
          password: ${USER_VAUGIE_G_PASSWORD}
        - id: "i_dont_know"
          name: "Jeremy"
          password: ${USER_I_DONT_KNOW_PASSWORD}
        - id: "nasso"
          name: "Nassim"
          password: ${USER_NASSO_PASSWORD}
  authorizationStrategy:
    roleBased:
      roles:
        global:
        - assignments:
          - "chocolateen"
          name: "admin"
          permissions:
          - "Overall/Administer"
          description: "Marvin master"
        - assignments:
          - "i_dont_know"
          name: "ape"
          permissions:
          - "Overall/Read"
          - "Job/Build"
          - "Job/Workspace"
          - "Job/Read"
          description: "Pedagogical team member"
        - assignments:
          - "vaugie_g"
          name: "gorilla"
          permissions:
          - "Overall/Read"
          - "Job/Read"
          - "Job/Cancel"
          - "Job/Build"
          - "Job/Delete"
          - "Job/Create"
          - "Job/Configure"
          - "Job/Workspace"
          - "Job/Move"
          description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
        - assignments:
          - "nasso"
          name: "assist"
          permissions:
          - "Overall/Read"
          - "Job/Read"
          - "Job/Workspace"
          description: "Assistant"

jobs:
  - file: /var/jenkins_home/config/job_dsl.groovy